create or replace NONEDITIONABLE TRIGGER TRG_UP_MEM_FOR_FINISH_DRIVE 
AFTER INSERT ON FINISH_DRIVE_TBL -- INSERT 먼저 실행 후에 BEGIN 진행
REFERENCING OLD AS O NEW AS N
FOR EACH ROW
DECLARE

    V_TEL           VARCHAR2(13);

BEGIN
    
    SELECT T1.R_TEL
    INTO V_TEL
    FROM DR_MEMBER_TBL T1, RESERVATION_TBL T2
    WHERE T1.R_TEL = T2.R_TEL
    ;
    
    IF (:N.F_GUBUN = 2) THEN
    
        UPDATE DR_MEMBER_TBL
        SET MEM_POINT = MEM_POINT - ROUND((MEM_POINT * 0.1), 0)
        WHERE R_TEL = V_TEL
        ;
        
    END IF;

END;